class Commands:
    MIRROR = "unduh"
    LEECH= "unggah"
    COPY = "salin"
    CONFIG= "konfig"
    MYFILES= "berkas"
    EXEC = "exec"
    GETLOGS = "logs"
    SERVER = "stats"
    START = "start"
    SPEEDTEST = "speedtest"
    TEST= "test"
    CRLDATA = "cleardata"
    RESTART= "restart"
