
name: HILMAN

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY2}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME2}}
          heroku_email: ${{secrets.HEROKU_EMAIL2}}
          usedocker: true
          docker_heroku_process_type: worker
          stack: "container"
          region: "us"
